name: Update Podfiles

on:
  push:
    branches:
      - main
    paths:
      - 'package.json'
jobs:
  update_podfile:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Check for version change
        run: |
          VERSION_CHANGE=$(git diff ${{ github.event.before }} ${{ github.sha }} -- package.json | grep -E "^\+.*\"version\":")
          echo "Version change detected: $VERSION_CHANGE"
          if [ -z "$VERSION_CHANGE" ]; then
            echo "No version change detected, exiting."
            exit 0
          fi
      - name: Use Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Install CocoaPods
        run: sudo gem install cocoapods
      - name: Update Podfiles
        run: APP_DIR=Example yarn pod-update && APP_DIR=FabricExample yarn pod-update
